Перед вами введение в синтаксис PyTorch, заимствованное с [официального сайта](https://pytorch.org/tutorials/index.html) фрэймворка

По [данной](https://rickwierenga.com/blog/machine%20learning/numpy-vs-pytorch-linalg.html) ссылке находится также очень познавательная статья о сравнении библиотек `numpy` и `PyTorch` 


In [ ]:
%matplotlib inline


Introduction to PyTorch
***********************

Introduction to Torch's tensor library
======================================

All of deep learning is computations on tensors, which are
generalizations of a matrix that can be indexed in more than 2
dimensions. We will see exactly what this means in-depth later. First,
let's look what we can do with tensors.



In [ ]:
# Author: Robert Guthrie

import torch

torch.manual_seed(1)

Creating Tensors
~~~~~~~~~~~~~~~~

Tensors can be created from Python lists with the torch.tensor()
function.




In [ ]:
import numpy as np

a = np.array([1, 2, 3], dtype=int)
a.astype(float)

array([1., 2., 3.])

In [ ]:
# torch.tensor(data) creates a torch.Tensor object with the given data.
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

# Creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.tensor(M_data)
print(M)

# Create a 3D tensor of size 2x2x2.
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


What is a 3D tensor anyway? Think about it like this. If you have a
vector, indexing into the vector gives you a scalar. If you have a
matrix, indexing into the matrix gives you a vector. If you have a 3D
tensor, then indexing into the tensor gives you a matrix!

A note on terminology:
when I say "tensor" in this tutorial, it refers
to any torch.Tensor object. Matrices and vectors are special cases of
torch.Tensors, where their dimension is 2 and 1 respectively. When I am
talking about 3D tensors, I will explicitly use the term "3D tensor".




In [ ]:
np.array([1,2,3])[0]

1

In [ ]:
# Index into V and get a scalar (0 dimensional tensor)
print(V[0])
# Get a Python number from it
print(V[0].item())

# Index into M and get a vector
print(M[0])

# Index into T and get a matrix
print(T[0])

tensor(1.)
1.0
tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.]])


You can also create tensors of other data types. To create a tensor of integer types, try
torch.tensor([[1, 2], [3, 4]]) (where all elements in the list are integers).
You can also specify a data type by passing in ``dtype=torch.data_type``.
Check the documentation for more data types, but
Float and Long will be the most common.




You can create a tensor with random data and the supplied dimensionality
with torch.randn()




In [ ]:
x = torch.randn((3, 4, 5))
print(x.shape)

torch.Size([3, 4, 5])


Operations with Tensors
~~~~~~~~~~~~~~~~~~~~~~~

You can operate on tensors in the ways you would expect.



In [ ]:
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])


See `the documentation <https://pytorch.org/docs/torch.html>`__ for a
complete list of the massive number of operations available to you. They
expand beyond just mathematical operations.

One helpful operation that we will make use of later is concatenation.




In [ ]:
a = np.array([1,2,3])
b = np.array([1,2,3])

np.concatenate([a, b])




array([1, 2, 3, 1, 2, 3])

In [ ]:
# By default, it concatenates along the first axis (concatenates rows)
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1], dim=0)
print(z_1.shape)

# Concatenate columns:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# second arg specifies which axis to concat along
z_2 = torch.cat([x_2, y_2], dim=1)
print(z_2)

# If your tensors are not compatible, torch will complain.  Uncomment to see the error
# torch.cat([x_1, x_2])

torch.Size([5, 5])
tensor([[ 0.6831,  0.6439, -1.5348, -0.0813,  1.5079,  1.1710,  0.6938,  0.8491],
        [ 0.1530, -0.3657,  0.0245,  0.2730,  0.3795,  0.0478,  1.3501,  0.0977]])


__Tensor__ -- это такой же массив, как и в __numpy.array__, размерность и тип данных которого мы можем задать. Tensor в отличие от numpy.array может вычисляться на __GPU__.

In [ ]:
import numpy as np
import torch

In [ ]:
N = 100
D_in = 50

dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

x = np.random.randn(N, D_in)
x_torch = torch.randn((N, D_in, 2), device=device, dtype=dtype)
print(x_torch.shape)
torch.tensor([1,2,3], device=device)

torch.Size([100, 50, 2])


tensor([1, 2, 3])

In [ ]:
x

array([[ 0.61373446,  1.27544833, -2.68340664, ...,  0.76133342,
         1.11680431,  1.08792903],
       [ 0.37948914, -0.39570526, -0.3515631 , ...,  1.86049029,
        -0.10374261, -0.0724359 ],
       [ 0.74927422, -0.02587014, -0.70616885, ...,  0.21847611,
        -0.83129116, -0.28469497],
       ...,
       [-0.80295689, -0.16598718,  1.38496947, ...,  0.32175487,
         0.75997257, -1.30992733],
       [ 0.21710362,  1.45658188,  0.12217248, ...,  1.09644054,
         0.44446769, -0.65360141],
       [-0.50156688,  0.94336119, -0.05296278, ...,  0.32903031,
         0.10095635,  0.63842852]])

In [ ]:
x_torch

tensor([[[-0.5928,  0.6358],
         [-3.0913,  0.6888],
         [-1.4958,  0.6277],
         ...,
         [-0.8438, -2.3038],
         [ 0.2119, -2.6601],
         [-0.9947, -0.5137]],

        [[ 2.1362,  2.8138],
         [ 0.0456, -0.1192],
         [ 0.4656, -1.4708],
         ...,
         [-0.0699, -0.5120],
         [ 1.3522,  0.4608],
         [-0.2693, -0.2583]],

        [[ 1.0727,  0.1080],
         [-1.0975,  1.7769],
         [ 0.2404, -1.1616],
         ...,
         [-0.4240, -0.3659],
         [ 0.1866, -0.8113],
         [-0.1190,  0.3810]],

        ...,

        [[ 0.5284,  0.5654],
         [-0.2487,  0.6009],
         [-0.7430, -0.1331],
         ...,
         [ 0.0437,  0.2684],
         [ 0.9439, -0.2326],
         [-1.0365, -0.2475]],

        [[ 1.3986,  0.8620],
         [-0.1671,  0.6372],
         [ 0.7938,  0.8623],
         ...,
         [ 0.8048, -1.0643],
         [ 0.6602, -1.3112],
         [ 0.1318,  0.9350]],

        [[-0.5524, -1.5529],
       

In [ ]:
np.ones((N, D_in))

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [ ]:
x_torch = torch.Tensor(np.ones((N, D_in)))
x_torch

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]])

На [странице](https://pytorch.org/docs/stable/tensors.html) приведено описания различных численных форматов `torch.Tensor`

In [ ]:
x_torch = torch.FloatTensor([1, 2, 3])
x_torch

tensor([1., 2., 3.])

In [ ]:
x1 = torch.IntTensor([1, 2, 3])
x2 = torch.FloatTensor([3, 4, 5])

In [ ]:
x1, x2

(tensor([1, 2, 3], dtype=torch.int32), tensor([3., 4., 5.]))

В PyTorch можно найти много операций, которые похожи на то, что есть в numpy :
```
- torch.add (np.add) -> сложение тензоров (поэлементное)
- torch.sub (np.subtract) -> вычитание (поэлементное)
- torch.mul (np.multiply) -> умнажение скаляров / матриц (поэлементное)
- torch.mm (np.matmul) -> перемножение матриц
- torch.ones (np.ones) -> создание тензора из единиц
```

Давайте попробуем вышепересчисленные операции

In [ ]:
a = torch.tensor([1,2,3])
b = torch.ones_like(a)
print(a, b)
torch.add(a, b), a.add(b)

tensor([1, 2, 3]) tensor([1, 1, 1])


(tensor([2, 3, 4]), tensor([2, 3, 4]))

In [ ]:
x1 = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
x1

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
x2 = torch.FloatTensor([[7, 8], [9, 1], [2, 3]])
x2

tensor([[7., 8.],
        [9., 1.],
        [2., 3.]])

In [ ]:
out = torch.mm(x1, x2)
out

tensor([[31., 19.],
        [85., 55.]])

In [ ]:
torch.ones((3, 3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
print(torch.ones_like(x1))
print()
print(torch.ones_like(x2))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


Reshaping Tensors
~~~~~~~~~~~~~~~~~

Use the .view() method to reshape a tensor. This method receives heavy
use, because many neural network components expect their inputs to have
a certain shape. Often you will need to reshape before passing your data
to the component.




In [ ]:
x = torch.tensor([[[1,2,3],
                  [3,4,5]],
                
                [[1,2,3],
                  [3,4,5]]])
print(x.shape)
x.view(3, -1)
# x.shape

torch.Size([2, 2, 3])


tensor([[1, 2, 3, 3],
        [4, 5, 1, 2],
        [3, 3, 4, 5]])

In [ ]:
x = torch.randn(2, 3, 4)
print(x, '\n\n')
print(x.view(2, 12))  # Reshape to 2 rows, 12 columns
# Same as above.  If one of the dimensions is -1, its size can be inferred
print(x.view(2, -1))

tensor([[[ 1.6730,  1.2731,  0.4292, -1.1909],
         [-0.3623,  0.9516, -0.8904,  1.5802],
         [-0.0746, -0.2861,  1.0203, -1.3425]],

        [[ 0.3347,  0.5698,  0.4372, -0.5147],
         [-0.0286, -1.6158,  0.2189, -0.0166],
         [ 0.0526, -0.3196, -0.0254, -0.4843]]]) 


tensor([[ 1.6730,  1.2731,  0.4292, -1.1909, -0.3623,  0.9516, -0.8904,  1.5802,
         -0.0746, -0.2861,  1.0203, -1.3425],
        [ 0.3347,  0.5698,  0.4372, -0.5147, -0.0286, -1.6158,  0.2189, -0.0166,
          0.0526, -0.3196, -0.0254, -0.4843]])
tensor([[ 1.6730,  1.2731,  0.4292, -1.1909, -0.3623,  0.9516, -0.8904,  1.5802,
         -0.0746, -0.2861,  1.0203, -1.3425],
        [ 0.3347,  0.5698,  0.4372, -0.5147, -0.0286, -1.6158,  0.2189, -0.0166,
          0.0526, -0.3196, -0.0254, -0.4843]])


```
- torch.reshape или tensor.view (где tensor-это объект torch.tensor) -> изменения порядка элементов в тензоре, не путать с транспонированием.
```

In [ ]:
print(x1, '\n\n')
x1.t()

tensor([[1., 2., 3.],
        [4., 5., 6.]]) 




tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [ ]:
x1.view(3, 2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [ ]:
torch.reshape(x1, (-1, 2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [ ]:
x1.view((-1, 2))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [ ]:
x1 = x1.reshape_as(x2)
x1

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [ ]:
x1 = x1.type(torch.int)

print(f'x1 type: {x1.dtype} \nx2 type: {x2.dtype} \n\n')
x1 + x2

x1 type: torch.int32 
x2 type: torch.float32 




tensor([[ 8., 10.],
        [12.,  5.],
        [ 7.,  9.]])